

CITY_TO_AIRPORT = {
    # United States - Major Cities
    "atlanta": "ATL",
    "new york": "JFK",
    "nyc": "JFK",
    "new york city": "JFK",
    "los angeles": "LAX",
    "la": "LAX",
    "chicago": "ORD",
    "miami": "MIA",
    "san francisco": "SFO",
    "sf": "SFO",
    "seattle": "SEA",
    "boston": "BOS",
    "washington": "DCA",
    "dc": "DCA",
    "washington dc": "DCA",
    "houston": "IAH",
    "dallas": "DFW",
    "phoenix": "PHX",
    "denver": "DEN",
    "las vegas": "LAS",
    "vegas": "LAS",
    "detroit": "DTW",
    "minneapolis": "MSP",
    "philadelphia": "PHL",
    "orlando": "MCO",
    "san diego": "SAN",
    "portland": "PDX",
    "austin": "AUS",
    "nashville": "BNA",
    "charlotte": "CLT",
    "tampa": "TPA",
    "st louis": "STL",
    "kansas city": "MCI",
    "columbus": "CMH",
    "indianapolis": "IND",
    "cleveland": "CLE",
    "san jose": "SJC",
    "sacramento": "SMF",
    "pittsburgh": "PIT",
    "milwaukee": "MKE",
    "raleigh": "RDU",
    "new orleans": "MSY",
    "memphis": "MEM",
    "oklahoma city": "OKC",
    "louisville": "SDF",
    "baltimore": "BWI",
    "fort lauderdale": "FLL",
    "salt lake city": "SLC",
    "honolulu": "HNL",
    "anchorage": "ANC",
    
    # Canada
    "toronto": "YYZ",
    "vancouver": "YVR",
    "montreal": "YUL",
    "calgary": "YYC",
    "edmonton": "YEG",
    "ottawa": "YOW",
    "winnipeg": "YWG",
    "halifax": "YHZ",
    "quebec": "YQB",
    "victoria": "YYJ",
    
    # Japan
    "tokyo": "NRT",
    "tokyo narita": "NRT",
    "tokyo haneda": "HND",
    "kyoto": "KIX",
    "osaka": "KIX",
    # Note: "japan" country mapping removed - users must specify a city
    "sapporo": "CTS",
    "fukuoka": "FUK",
    "nagoya": "NGO",
    "sendai": "SDJ",
    "hiroshima": "HIJ",
    "okinawa": "OKA",
    
    # China
    "beijing": "PEK",
    "shanghai": "PVG",
    "guangzhou": "CAN",
    "shenzhen": "SZX",
    "chengdu": "CTU",
    "hong kong": "HKG",
    "macau": "MFM",
    "taipei": "TPE",
    # Note: "taiwan" country mapping removed - users must specify a city
    
    # South Korea
    "seoul": "ICN",
    "busan": "PUS",
    "jeju": "CJU",
    
    # Southeast Asia
    "singapore": "SIN",
    "bangkok": "BKK",
    "kuala lumpur": "KUL",
    "jakarta": "CGK",
    "manila": "MNL",
    "ho chi minh city": "SGN",
    "hanoi": "HAN",
    "phnom penh": "PNH",
    "yangon": "RGN",
    "vientiane": "VTE",
    
    # India
    "mumbai": "BOM",
    "delhi": "DEL",
    "bangalore": "BLR",
    "chennai": "MAA",
    "hyderabad": "HYD",
    "kolkata": "CCU",
    "pune": "PNQ",
    "goa": "GOI",
    "kochi": "COK",
    "ahmedabad": "AMD",
    
    # Middle East
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "doha": "DOH",
    "riyadh": "RUH",
    "jeddah": "JED",
    "kuwait": "KWI",
    "beirut": "BEY",
    "tel aviv": "TLV",
    "istanbul": "IST",
    "ankara": "ESB",
    "cairo": "CAI",
    
    # Europe - Major Cities
    "london": "LHR",
    "paris": "CDG",
    "rome": "FCO",
    "madrid": "MAD",
    "berlin": "BER",
    "amsterdam": "AMS",
    "barcelona": "BCN",
    "munich": "MUC",
    "vienna": "VIE",
    "dublin": "DUB",
    "brussels": "BRU",
    "zurich": "ZRH",
    "copenhagen": "CPH",
    "stockholm": "ARN",
    "oslo": "OSL",
    "helsinki": "HEL",
    "warsaw": "WAW",
    "prague": "PRG",
    "budapest": "BUD",
    "athens": "ATH",
    "lisbon": "LIS",
    "milan": "MXP",
    "venice": "VCE",
    "naples": "NAP",
    "florence": "FLR",
    "edinburgh": "EDI",
    "glasgow": "GLA",
    "manchester": "MAN",
    "frankfurt": "FRA",
    "hamburg": "HAM",
    "brussels": "BRU",
    "geneva": "GVA",
    "lyon": "LYS",
    "nice": "NCE",
    "moscow": "SVO",
    "st petersburg": "LED",
    "krakow": "KRK",
    "porto": "OPO",
    "valencia": "VLC",
    "seville": "SVQ",
    "rotterdam": "RTM",
    "antwerp": "ANR",
    
    # Australia & New Zealand
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
    "perth": "PER",
    "adelaide": "ADL",
    "darwin": "DRW",
    "cairns": "CNS",
    "gold coast": "OOL",
    "auckland": "AKL",
    "wellington": "WLG",
    "christchurch": "CHC",
    
    # Latin America
    "mexico city": "MEX",
    "cancun": "CUN",
    "guadalajara": "GDL",
    "monterrey": "MTY",
    "sao paulo": "GRU",
    "rio de janeiro": "GIG",
    "buenos aires": "EZE",
    "lima": "LIM",
    "bogota": "BOG",
    "santiago": "SCL",
    "panama city": "PTY",
    "san jose costa rica": "SJO",
    "havana": "HAV",
    "santo domingo": "SDQ",
    "san juan": "SJU",
    "caracas": "CCS",
    "montevideo": "MVD",
    "quito": "UIO",
    "guayaquil": "GYE",
    "la paz": "LPB",
    "asuncion": "ASU",
    
    # Africa
    "johannesburg": "JNB",
    "cape town": "CPT",
    "cairo": "CAI",
    "casablanca": "CMN",
    "marrakech": "RAK",
    "nairobi": "NBO",
    "lagos": "LOS",
    "accra": "ACC",
    "addis ababa": "ADD",
    "dar es salaam": "DAR",
    "tunis": "TUN",
    "algiers": "ALG",
    
    # Other Major Cities
    "moscow": "SVO",
    "st petersburg": "LED",
    "kuala lumpur": "KUL",
    "jakarta": "CGK",
    "manila": "MNL",
    "ho chi minh": "SGN",
    "hanoi": "HAN",
}

